version: '2'
networks:
    bridge:

services:
  ca:
    image: rameshthoomu/fabric-ca-x86_64:x86_64-0.7.0-snapshot-f18b6b7
    command: sh -c 'fabric-ca-server start -b admin:adminpw' -d
    ports: 
      - 7054:7054
    environment: 
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    container_name: ca0

  orderer0:
    image: rameshthoomu/fabric-orderer-x86_64:x86_64-0.7.0-snapshot-509d8ed
    restart: unless-stopped
    environment: 
      - ORDERER_GENERAL_LEDGERTYPE=ram
      - ORDERER_GENERAL_MAXWINDOWSIZE=1000
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_LOGLEVEL=DEBUG
      - ORDERER_RAMLEDGER_HISTORY_SIZE=100
      - CONFIGTX_ORDERER_ORDERERTYPE=solo
      - CONFIGTX_ORDERER_ADDRESSES=[0.0.0.0:7050]
      - CONFIGTX_ORDERER_BATCHTIMEOUT=10s
      - CONFIGTX_ORDERER_BATCHSIZE_MAXMESSAGECOUNT=10
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    ports: 
      - 7050:7050
    container_name: orderer0
    networks: 
      - bridge

  peer0:
    image: rameshthoomu/fabric-peer-x86_64:x86_64-0.7.0-snapshot-509d8ed
    restart: unless-stopped
    environment: 
      - CORE_PEER_ID=peer0
      - CORE_PEER_NETWORKID=peer0
      - CORE_PEER_ADDRESSAUTODETECT=false
      - CORE_NEXT=true
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_ADDRESS=0.0.0.0:7051
      - CORE_PEER_COMMITTER_ENABLED=true
      - CORE_PEER_COMMITTER_LEDGER_ORDERER=orderer0:7050
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_DISCOVERY_PERIOD=60s
      - CORE_PEER_DISCOVERY_TOUCHPERIOD=60s
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=ERROR
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    volumes: 
      - /var/run:/host/var/run/
    command: peer node start -o orderer0:7050
    links: 
      - orderer0
      - ca
    ports: 
      - 7051:7051
      - 7053:7053
    container_name: peer0
    networks: 
      - bridge

  peer1:
    image: rameshthoomu/fabric-peer-x86_64:x86_64-0.7.0-snapshot-509d8ed
    restart: unless-stopped
    environment: 
      - CORE_PEER_ID=peer1
      - CORE_PEER_NETWORKID=peer1
      - CORE_PEER_ADDRESSAUTODETECT=false
      - CORE_NEXT=true
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_ADDRESS=0.0.0.0:7052
      - CORE_PEER_COMMITTER_ENABLED=true
      - CORE_PEER_COMMITTER_LEDGER_ORDERER=orderer0:7050
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_DISCOVERY_PERIOD=60s
      - CORE_PEER_DISCOVERY_TOUCHPERIOD=60s
      - CORE_PEER_DISCOVERY_ROOTNODE=0.0.0.0:7051
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=ERROR
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    volumes:
      - /var/run:/host/var/run/
    command: peer node start -o orderer0:7050
    links: 
      - orderer0
      - ca
      - peer0
    ports: 
      - 7052:7051
      - 7056:7053
    container_name: peer1
    networks: 
      - bridge
  cli:
    container_name: cli
    image: rameshthoomu/fabric-peer-x86_64:x86_64-0.7.0-snapshot-509d8ed
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_NEXT=true
      - CORE_PEER_ID=cli
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_ADDRESS=peer0:7051
      - CORE_PEER_GOSSIP_IGNORESECURITY=true
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash 
    volumes:
      - /var/run/:/host/var/run/
      - ./examples/:/opt/gopath/src/github.com/hyperledger/fabric/examples/
    depends_on:
      - orderer0
      - peer0
      - peer1
